import { Tour } from 'nextstepjs';

export const tourSteps: Tour[] = [
  {
    tour: 'onboarding',
    steps: [
      {
        icon: '🐰',
        title: 'Welcome to BunnyDB',
        content: 'Postgres-to-Postgres CDC replication. Quick tour — under 30 seconds.',
        side: 'bottom',
        showControls: true,
        showSkip: true,
      },
      {
        icon: '🔗',
        title: 'Peers',
        content: 'Your database connections live here.',
        selector: '#nav-peers',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 4,
        pointerRadius: 8,
      },
      {
        icon: '🪞',
        title: 'Mirrors',
        content: 'Active replication jobs. Real-time CDC streaming.',
        selector: '#nav-mirrors',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 4,
        pointerRadius: 8,
      },
      {
        icon: '⚙️',
        title: 'Settings',
        content: 'Manage users and change passwords.',
        selector: '#nav-settings',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 4,
        pointerRadius: 8,
      },
      {
        icon: '1️⃣',
        title: 'Add a Peer',
        content: 'Register your source and destination Postgres DBs.',
        selector: '#add-peer-btn',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        nextRoute: '/peers',
        pointerPadding: 6,
        pointerRadius: 8,
      },
      {
        icon: '🧪',
        title: 'Test It',
        content: 'Verify connectivity with one click before going live.',
        selector: '#peers-list',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '2️⃣',
        title: 'Create a Mirror',
        content: 'Pick source + destination, select tables, go.',
        selector: '#create-mirror-btn',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        nextRoute: '/mirrors',
        pointerPadding: 6,
        pointerRadius: 8,
      },
      {
        icon: '3️⃣',
        title: 'Monitor',
        content: 'Live status. Pause, resume, resync, view logs.',
        selector: '#mirrors-list',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '👤',
        title: 'Your Account',
        content: 'Admins can mutate. Readonly users can only view.',
        selector: '#user-menu',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 6,
        pointerRadius: 8,
      },
      {
        icon: '🎉',
        title: 'All set!',
        content: 'Add Peers → Create Mirror → Monitor. Restart anytime with the ? icon.',
        side: 'bottom',
        showControls: true,
        showSkip: false,
      },
    ],
  },
];
